services:
  Dbp\Relay\TemplateBundle\Command\TestCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\TemplateBundle\Controller\:
    resource: '../../Controller'
    autoconfigure: true
    autowire: true

  Dbp\Relay\TemplateBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\TemplateBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\TemplateBundle\Service\ExternalApi:
    autowire: true
    autoconfigure: true

  Dbp\Relay\TemplateBundle\Service\MyCustomService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\TemplateBundle\Service\PlaceProviderInterface:
    '@Dbp\Relay\TemplateBundle\Service\ExternalApi'
