services:
  DBP\API\StarterBundle\Command\TestCommand:
    autowire: true
    autoconfigure: true

  DBP\API\StarterBundle\DataProvider\PlaceCollectionDataProvider:
    tags: [{ name: 'api_platform.collection_data_provider'}]
    autowire: true

  DBP\API\StarterBundle\DataProvider\PlaceItemDataProvider:
    tags: ['api_platform.item_data_provider']
    autowire: true

  DBP\API\StarterBundle\Service\ExternalApi:
    autowire: true
    autoconfigure: true

  DBP\API\StarterBundle\Service\PlaceProviderInterface:
    '@DBP\API\StarterBundle\Service\ExternalApi'