services:
  Dbp\Relay\ExampleBundle\Command\TestCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ExampleBundle\ApiPlatform\:
    resource: '../../ApiPlatform'
    autoconfigure: true
    autowire: true

  Dbp\Relay\ExampleBundle\Service\ExternalApi:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ExampleBundle\HealthCheck\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ExampleBundle\Service\MyCustomService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ExampleBundle\Service\PlaceProviderInterface:
    '@Dbp\Relay\ExampleBundle\Service\ExternalApi'
