services:
  Dbp\Relay\TemplateBundle\Command\TestCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\TemplateBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']
    autowire: true

  Dbp\Relay\TemplateBundle\DataProvider\PlaceCollectionDataProvider:
    tags: [{ name: 'api_platform.collection_data_provider'}]
    autowire: true

  Dbp\Relay\TemplateBundle\DataProvider\PlaceItemDataProvider:
    tags: ['api_platform.item_data_provider']
    autowire: true

  Dbp\Relay\TemplateBundle\Service\ExternalApi:
    autowire: true
    autoconfigure: true

  Dbp\Relay\TemplateBundle\Service\MyCustomService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\TemplateBundle\Service\PlaceProviderInterface:
    '@Dbp\Relay\TemplateBundle\Service\ExternalApi'